// Generated by https://quicktype.io

export interface JSON {
    technologies: Technology[];
}

export interface Technology {
    name:        string;
    description: string;
    difficulty:  number;
    courses:     Course[];
}

export interface Course {
    code: string;
}